live_config_reload = true

import = [
  "~/.config/alacritty/tokyonight.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 8.0

[font.bold]
#family = "Hack Nerd Font"
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
#family = "Hack Nerd Font"
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
#family = "Hack Nerd Font"
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
#family = "Hack Nerd Font"
family = "FiraCode Nerd Font"
style = "Regular"

[window]
opacity = 0.7

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Control|Shift"

[mouse]
hide_when_typing = true

[shell]
program = "zsh"
