windowrule = workspace special:spotify, match:class ^(Spotify)$
windowrule = workspace special:browser, match:class ^(google-chrome)$

windowrule = opacity 0.8, match:class ^(code)$
windowrule = opacity 0.8, match:class ^(com\.mitchellh\.ghostty)$
windowrule = opacity 0.8, match:class ^(Horizon-client)$
windowrule = opacity 0.7, match:class ^(google-chrome)$

windowrule = immediate on, match:class ^(Horizon-client)$
