workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1
workspace = 6, monitor:DP-2
workspace = 7, monitor:DP-2
workspace = 8, monitor:DP-2
workspace = 9, monitor:DP-2
workspace = 0, monitor:DP-2

unbind = SUPER, H
unbind = SUPER, J
unbind = SUPER, K
unbind = SUPER, L
unbind = SUPER SHIFT, H
unbind = SUPER SHIFT, J
unbind = SUPER SHIFT, K
unbind = SUPER SHIFT, L
bindd = SUPER, H, Move focus left, movefocus, l
bindd = SUPER, J, Move focus down, movefocus, d
bindd = SUPER, K, Move focus up, movefocus, u
bindd = SUPER, L, Move focus right, movefocus, r
bindd = SUPER SHIFT, H, Swap window to the left, swapwindow, l
bindd = SUPER SHIFT, L, Swap window to the right, swapwindow, r
bindd = SUPER SHIFT, K, Swap window up, swapwindow, u
bindd = SUPER SHIFT, J, Swap window down, swapwindow, d

unbind = SUPER, M
unbind = SUPER CTRL ALT, M
unbind = SUPER, B
unbind = SUPER CTRL ALT, B
unbind = SUPER, W
unbind = SUPER CTRL ALT, W
unbind = SUPER, I
unbind = SUPER CTRL ALT, I

bind = SUPER, M, togglespecialworkspace, spotify
bind = SUPER CTRL ALT, M, movetoworkspace, special:spotify
bind = SUPER, B, togglespecialworkspace, browser
bind = SUPER CTRL ALT, B, movetoworkspace, special:browser
bind = SUPER, W, togglespecialworkspace, work
bind = SUPER CTRL ALT, W, movetoworkspace, special:work
bind = SUPER, I, togglespecialworkspace, idolo
bind = SUPER CTRL ALT, I, movetoworkspace, special:idolo
