# Fixing popup size issue
windowrule = size 50% 50%, match:class (.*jetbrains.*)$, match:title ^$, match:float 1

# Fix tab dragging (always have a single space character as their title)
windowrule = no_initial_focus on, match:class ^(.*jetbrains.*)$, match:title ^\\s$
windowrule = no_focus on, match:class ^(.*jetbrains.*)$, match:title ^\\s$
